export const labCopy = {
  en: {
    tabs: {
      ecosystem: "Ecosystem overview",
      godl: "GODL token",
      usgd: "USGD stablecoin",
      gdl: "GDL governance",
      faq: "Investor Q&A",
      soon: "Soon",
    },
    hero: {
      badge: "GODL Labs Laboratory",
      title: "Ecosystem Dashboard Lab",
      description:
        "Interactive investor dashboard rebuilt as React components: gold price simulator, staking yield model, token flow overview, USGD collateral view, and institutional Q&A.",
      simulatorTitle: "Gold spot simulator",
      simulatorHint: "Move slider to simulate",
      sliderLabel: "Gold price / oz",
      sliderAria: "Gold price simulator",
    },
    units: {
      perOz: "/ oz",
      annualEstimate: "/ yr est.",
      perMonth: "/ mo",
      atPerOz: (price) => `at ${price} / oz`,
      year: (count) => `${count} ${count === 1 ? "year" : "years"}`,
    },
    ecosystem: {
      kpis: {
        reserve: ["Gold reserve", "1M+ oz", "Tanzania JORC + Brazil portfolio"],
        projection: ["Annual projection", "46K oz", "Tanzania grade 4.15 g/t"],
        revenue: ["Annual revenue est."],
        fdv: ["GDL FDV", "$150M", "at $0.15 / token, always disclosed"],
        raise: ["Raise target", "$10-15M", "TGE September 2026+"],
        contracts: ["Smart contracts", "BSC", "CertiK audit in progress"],
      },
      mineTitle: "Mine portfolio",
      tanzaniaStatus: "JORC audited · live",
      tanzaniaDescription:
        "1M oz reserve, 4.15 g/t gold grade, 46K oz per year projected, mining licence E734429 via JICUN INTERNATIONAL.",
      brazilStatus: "Portfolio asset",
      brazilValue: "Unpriced upside",
      brazilDescription: "Wynson Group portfolio, pre-JORC, not counted in current projections or valuations.",
      workTitle: "How the ecosystem works",
      workCards: [
        [
          "Physical gold mined and refined",
          "Tanzania mine to ALTENEEN REFINERY, 99.99% LBMA purity, Ferrari Vault custody in the GCC, and immediate price hedge via Standard Chartered trading desk on staking.",
        ],
        [
          "Standard Chartered token layer and hedging",
          "Minting, digital custody, and distribution of GODL on BSC. Trading desk executes immediate hedge on each staking event.",
        ],
        [
          "USGD minted",
          "$1 subscribed equals 1 USGD on BSC after launch, with 1:1.5 overcollateralization. Pre-USGD launch subscriptions settle in USDT.",
        ],
        [
          "GODL issued",
          "Approximately 160K GODL, mapped 1:1 to troy ounces, tracking London gold through XAUT and PAXG references plus arbitrage bots.",
        ],
        [
          "Revenue waterfall",
          "Opex first, then 5% net profit to GDL buyback-and-burn, and up to 31% to GODL stakers. DeFi rewards run separately through GDL allocation.",
        ],
        [
          "DeFi layer",
          "BSC and PancakeSwap pool design is retained as lab modelling. Public DeFi and swap access remain staged for launch.",
        ],
      ],
      infrastructureTitle: "Infrastructure stack",
      infrastructureItems: [
        ["Smart contract audit", "CertiK"],
        ["Real asset audit", "ROMA.US"],
        ["GDL digital custody", "BitGo"],
        ["GODL tokenisation & custody", "Standard Chartered"],
        ["Physical vault & insurance", "Ferrari Vault"],
        ["Refinery", "ALTENEEN REFINERY"],
        ["DEX / swap", "PancakeSwap (BSC)"],
        ["Mining licence holder", "JICUN INTERNATIONAL"],
      ],
    },
    godl: {
      introTitle: "GODL is the flagship launch token",
      introDescription:
        "GODL gives institutional investors on-chain exposure to gold mining revenue, with monthly yield payments tokenised and distributed through the platform. Prior to USGD launch, subscriptions and yield payments settle in USDT.",
      regulatedLabel: "Regulated fund management:",
      regulatedDescription:
        "All funds raised by GODL will be managed by Wynson Asset Management Ltd, a Hong Kong SFC-regulated entity.",
      kpis: {
        price: ["GODL token price", "Tracks 1 troy oz gold spot"],
        supply: ["Token supply", "~160,000", "1:1 troy oz mapping"],
        marketCap: ["Market cap FDV"],
        maxYield: ["Max staking yield", "31% pa", "Paid monthly, on-chain"],
        custody: ["Token custody and minting", "Standard Chartered", "Minting, custody, distribution"],
        swap: ["Swap", "PancakeSwap", "Modelled lab layer, not public launch"],
      },
      yieldTitle: "Where does the yield come from?",
      flowSteps: [
        [
          "Gold mine generates annualised return",
          "Based on 46K oz per year projected from the Tanzania JORC-audited reserve. Revenue is designed to be audited and recorded on-chain monthly via proof-of-reserve.",
        ],
        [
          "Revenue waterfall activates",
          "Operational expenses are settled first. A share of net profit routes to GDL buyback-and-burn, then remaining yield is distributed by staking tier.",
        ],
        ["Yield distributed to GODL stakers", "Real mining revenue rather than inflationary emissions. Before USGD launch, payments are modelled in USDT."],
        ["DeFi rewards are separate", "Liquidity mining incentives are funded by GDL allocation and are independent from mine revenue in this lab model."],
      ],
      calculatorTitle: "Staking tier calculator",
      lockLabel: (months) => `${months}-month lock`,
      tierShortLabel: (months, rate) => `${months}-month - ${rate}% pa`,
      annualized: "pa annualised",
      investmentUsd: "Investment USD",
      investmentPeriod: "Investment period",
      metrics: {
        investment: "Investment",
        stakingTier: "Staking tier",
        period: "Investment period",
        entryPrice: "Gold price at entry",
        annualYield: "Annual yield",
        monthlyPayment: "Monthly payment",
        totalYield: "Total yield over period",
        totalReturn: "Total return principal + yield",
        tokenValueChange: "GODL token value change on your position",
        totalExit: "Total position at exit tokens + yield",
      },
      priceScenarioTitle: "Gold price scenario",
      priceScenarioDescription: (entry) =>
        `Yield is fixed by staking tier. GODL token value moves with the simulated gold exit price, while the staking entry price is locked at ${entry} / oz.`,
      scenarioCards: {
        entry: ["Gold entry price", "At staking time"],
        exit: ["Simulated exit price", "From lab slider"],
        delta: ["Token price gain / loss", "Per oz vs entry"],
      },
      sensitivityTitle: "Gold price sensitivity",
      sensitivity: {
        spot: "Gold spot price",
        godlPrice: "GODL token price 1:1 oz",
        marketCap: "Market cap 160K tokens",
        revenue: "Annual mine revenue 46K oz",
        sampleYield: "31% yield on $100K, 12-month stake",
        sampleYieldValue: "$31,000 / yr · $2,583 / mo",
      },
    },
    usgd: {
      kpis: {
        peg: ["Peg", "$1.00 USD", "Does not move with gold"],
        ratio: ["Collateral ratio", "1 : 1.5", "150% gold-backed at baseline"],
        standard: ["Gold standard", "99.99%", "LBMA purity"],
        issuance: ["Issuance", "$1 = 1 USGD", "On subscription after launch"],
        prelaunch: ["Pre-launch", "USDT", "All subscriptions settle in USDT"],
        chain: ["Blockchain", "BSC", "Current contract scope"],
      },
      prelaunchLabel: "Pre-launch settlement:",
      prelaunchDescription:
        "Prior to USGD going live, gold subscriptions and yield payments are processed in USDT. USGD is a staged upgrade to the same on-chain flow.",
      stableTitle: "USGD vs other stablecoins",
      fiatTag: "Fiat-backed",
      fiatDescription: "Backed by USD or short-term treasuries. Peg depends on issuer trust and banking counterparties.",
      usgdDescription: "Planned 150% collateralization by physical gold, with Ferrari Vault custody and closed-loop redemption.",
      lifecycleTitle: "USGD lifecycle",
      lifecycle: [
        ["Subscription", "Investor sends USDT before launch. Once live, 1 USGD is minted on BSC per subscribed dollar with gold collateral backing."],
        ["Gold fund entry", "USGD, or USDT before launch, is the gateway to the GODL staking program."],
        ["DeFi utility", "The lab model includes USDT-USGD, GDL-USGD, and GODL-USGD pools for staged future utility."],
        ["Redemption", "Principal and earnings are credited in USGD after launch or USDT before launch."],
        ["Proof of reserve", "Monthly physical inventory audit data is designed to be uploaded on-chain for public verification."],
      ],
      bufferTitle: "Collateral buffer",
      bufferDescription: "Move the lab gold price slider to model how the collateral buffer changes relative to the $1 peg.",
      metrics: {
        goldPrice: "Gold price",
        backing: "Gold backing per $1 USGD",
        buffer: "Collateral buffer above peg",
        fall: "Gold must fall this much to break peg",
        status: "USGD peg status",
        fullyBacked: "Fully backed",
        belowTarget: "Below target collateral",
        excess: "excess",
      },
    },
    gdl: {
      title: "GDL Tokenomics - Coming Soon",
      description:
        "The GDL governance and incentive token structure is being finalised. Full allocation, vesting, and buyback mechanics will be published ahead of TGE.",
      kpis: [
        ["Total supply", "1B", "Fixed, no new minting"],
        ["Private sale price", "$0.15", "Per GDL token"],
        ["FDV at raise price", "$150M", "Always disclosed"],
        ["TGE", "Sept 2026+", "Full details at TGE"],
      ],
    },
    faq: {
      intro: "Confirmed answers to common institutional investor questions in the GODL Labs laboratory dashboard.",
      items: [
        [
          "Are you VARA licensed?",
          "Fraktiq DMCC is our Dubai exchange entity. The VARA licence application is pre-approved and currently in the final stages of being formalised. The dashboard does not claim an active licence at this time.",
        ],
        [
          "Who audited the gold reserve?",
          "GMRCS under the JORC Code (2012), with report issued in 2023. JICUN INTERNATIONAL holds the current mining licence E734429, and a fresh 2026 JORC update is in progress.",
        ],
        [
          "What is the annual gold production?",
          "46,000 oz per year projected from the Tanzania JORC reserve, based on a 1M oz reserve and 4.15 g/t grade. The Brazil portfolio is not included in current projections or valuations.",
        ],
        ["Who holds the physical gold?", "Ferrari Vault in the GCC. The physical gold is refined to 99.99% LBMA standard and insured by Ferrari for $225M."],
        [
          "What is Standard Chartered's exact role?",
          "Standard Chartered handles minting, digital custody, and distribution of the GODL RWA token on BSC. Its trading desk also executes an immediate price hedge on each staking event.",
        ],
        [
          "Where does the GODL yield come from?",
          "Yield is modelled from audited gold mine revenue and an AI gold hedge grid trading strategy. DeFi pool rewards are separate and funded by the GDL incentive allocation.",
        ],
        [
          "What currency is used for subscriptions and yield payments?",
          "Before USGD launch, subscriptions and yield payments are settled in USDT. Once USGD is live, USGD becomes the exclusive gateway with the same on-chain flow.",
        ],
        ["What blockchain are you on?", "BSC is used for the current contract scope covering GODL, USGD, and GDL. Cross-chain expansion is in planning only."],
        [
          "When is the TGE?",
          "GDL Token Generation Event is planned for September 2026 onwards, after infrastructure and regulatory clarity are ready for market.",
        ],
        [
          "How do I subscribe to GODL?",
          "Institutional users complete KYC/KYB, sign subscription documents, wire USD or transfer USDC/USDT, select the lock tranche, receive GODL to custody, and then receive monthly yield in USDT or USGD after launch.",
        ],
      ],
    },
    footer: {
      line1: "GODL Labs Ltd · Cayman Islands · Confidential lab view for institutional investor use · May 2026",
      line2: "Projected numbers are forward-looking estimates. Brazil mine portfolio is not reflected in financial figures.",
    },
  },
  zh: {
    tabs: {
      ecosystem: "生态总览",
      godl: "GODL 代币",
      usgd: "USGD 稳定币",
      gdl: "GDL 治理",
      faq: "投资者问答",
      soon: "待开放",
    },
    hero: {
      badge: "GODL Labs 实验室",
      title: "生态仪表盘实验室",
      description: "以 React 组件重构的交互式投资者仪表盘，包含金价模拟、质押收益模型、代币流转概览、USGD 抵押视图与机构问答。",
      simulatorTitle: "黄金现货模拟器",
      simulatorHint: "拖动滑块进行模拟",
      sliderLabel: "金价 / 盎司",
      sliderAria: "黄金价格模拟器",
    },
    units: {
      perOz: "/ 盎司",
      annualEstimate: "/ 年预估",
      perMonth: "/ 月",
      atPerOz: (price) => `按 ${price} / 盎司`,
      year: (count) => `${count} 年`,
    },
    ecosystem: {
      kpis: {
        reserve: ["黄金储量", "100万+ 盎司", "坦桑尼亚 JORC + 巴西资产组合"],
        projection: ["年度产量预估", "4.6万盎司", "坦桑尼亚品位 4.15 g/t"],
        revenue: ["年度收入估算"],
        fdv: ["GDL FDV", "1.5亿美元", "按 $0.15 / 枚披露"],
        raise: ["融资目标", "1000-1500万美元", "TGE 预计 2026 年 9 月之后"],
        contracts: ["智能合约", "BSC", "CertiK 审计推进中"],
      },
      mineTitle: "矿区资产组合",
      tanzaniaStatus: "JORC 审计 · 运行中",
      tanzaniaDescription: "100万盎司储量，黄金品位 4.15 g/t，预计年产 4.6万盎司，采矿许可证 E734429 由 JICUN INTERNATIONAL 持有。",
      brazilStatus: "组合资产",
      brazilValue: "未计价上行空间",
      brazilDescription: "Wynson Group 资产组合，处于 JORC 前阶段，暂不计入当前产量预测与估值。",
      workTitle: "生态系统运行方式",
      workCards: [
        [
          "实体黄金开采与精炼",
          "坦桑尼亚矿区黄金进入 ALTENEEN REFINERY 精炼，达到 99.99% LBMA 纯度，由 GCC 地区 Ferrari Vault 托管，并在质押时通过 Standard Chartered 交易台即时进行价格对冲。",
        ],
        ["Standard Chartered 代币层与对冲", "负责 GODL 在 BSC 上的铸造、数字托管与分发；交易台在每次质押事件中执行即时对冲。"],
        ["USGD 铸造", "上线后每 1 美元认购对应 1 USGD，采用 1:1.5 超额抵押。USGD 上线前，认购以 USDT 结算。"],
        ["GODL 发行", "约 16 万枚 GODL，按 1:1 映射金衡盎司，并参考 XAUT、PAXG 与套利机制跟踪伦敦金价格。"],
        ["收入分配", "先覆盖运营成本，再将 5% 净利润用于 GDL 回购销毁，最高 31% 分配给 GODL 质押用户。DeFi 激励由 GDL 额度独立支持。"],
        ["DeFi 层", "BSC 与 PancakeSwap 池设计作为实验室模型保留，公开 DeFi 与兑换入口仍处于分阶段开放前状态。"],
      ],
      infrastructureTitle: "基础设施栈",
      infrastructureItems: [
        ["智能合约审计", "CertiK"],
        ["实体资产审计", "ROMA.US"],
        ["GDL 数字托管", "BitGo"],
        ["GODL 代币化与托管", "Standard Chartered"],
        ["实体金库与保险", "Ferrari Vault"],
        ["精炼厂", "ALTENEEN REFINERY"],
        ["DEX / 兑换", "PancakeSwap (BSC)"],
        ["采矿许可证持有人", "JICUN INTERNATIONAL"],
      ],
    },
    godl: {
      introTitle: "GODL 是首发核心代币",
      introDescription: "GODL 为机构投资者提供链上黄金矿业收益敞口，月度收益通过平台代币化并发放。USGD 上线前，认购与收益支付均以 USDT 结算。",
      regulatedLabel: "受监管基金管理：",
      regulatedDescription: "GODL 募集资金将由香港 SFC 监管实体 Wynson Asset Management Ltd 管理。",
      kpis: {
        price: ["GODL 代币价格", "跟踪 1 金衡盎司黄金现货"],
        supply: ["代币供应量", "约 160,000", "1:1 映射金衡盎司"],
        marketCap: ["市值 FDV"],
        maxYield: ["最高质押收益", "31% 年化", "按月链上发放"],
        custody: ["代币托管与铸造", "Standard Chartered", "铸造、托管、分发"],
        swap: ["兑换", "PancakeSwap", "实验室模型层，暂非公开开放"],
      },
      yieldTitle: "收益从哪里来？",
      flowSteps: [
        ["金矿产生年化收益", "基于坦桑尼亚 JORC 审计储量预计年产 4.6万盎司。收入设计为按月审计并通过储备证明记录到链上。"],
        ["收入分配机制启动", "先结算运营支出，再将部分净利润路由至 GDL 回购销毁，剩余收益按质押档位分配。"],
        ["收益分配给 GODL 质押用户", "收益来自真实矿业收入，而非通胀式排放。USGD 上线前，收益以 USDT 模型结算。"],
        ["DeFi 奖励独立计算", "流动性挖矿激励来自 GDL 分配额度，与本实验室模型中的矿业收入相互独立。"],
      ],
      calculatorTitle: "质押档位计算器",
      lockLabel: (months) => `${months}个月锁仓`,
      tierShortLabel: (months, rate) => `${months}个月 - 年化 ${rate}%`,
      annualized: "年化",
      investmentUsd: "投入金额 USD",
      investmentPeriod: "投资周期",
      metrics: {
        investment: "投入金额",
        stakingTier: "质押档位",
        period: "投资周期",
        entryPrice: "入场金价",
        annualYield: "年度收益",
        monthlyPayment: "月度收益",
        totalYield: "周期总收益",
        totalReturn: "本金 + 收益合计",
        tokenValueChange: "你持仓中的 GODL 价值变化",
        totalExit: "退出时总代币价值 + 收益",
      },
      priceScenarioTitle: "金价情景",
      priceScenarioDescription: (entry) => `收益由质押档位固定。GODL 代币价值随模拟退出金价变化，质押入场价格锁定为 ${entry} / 盎司。`,
      scenarioCards: {
        entry: ["入场金价", "质押时价格"],
        exit: ["模拟退出价格", "来自实验室滑块"],
        delta: ["代币价格涨跌", "相对入场价 / 盎司"],
      },
      sensitivityTitle: "金价敏感度",
      sensitivity: {
        spot: "黄金现货价格",
        godlPrice: "GODL 代币价格 1:1 盎司",
        marketCap: "16 万枚代币市值",
        revenue: "4.6万盎司年矿业收入",
        sampleYield: "$100K 质押 12 个月、31% 年化收益",
        sampleYieldValue: "$31,000 / 年 · $2,583 / 月",
      },
    },
    usgd: {
      kpis: {
        peg: ["锚定", "$1.00 USD", "不随金价波动"],
        ratio: ["抵押比例", "1 : 1.5", "基准为 150% 黄金抵押"],
        standard: ["黄金标准", "99.99%", "LBMA 纯度"],
        issuance: ["发行", "$1 = 1 USGD", "上线后按认购金额铸造"],
        prelaunch: ["上线前", "USDT", "所有认购先以 USDT 结算"],
        chain: ["区块链", "BSC", "当前合约范围"],
      },
      prelaunchLabel: "上线前结算：",
      prelaunchDescription: "USGD 正式上线前，黄金认购与收益支付均以 USDT 处理。USGD 是同一链上流程的阶段性升级。",
      stableTitle: "USGD 与其他稳定币",
      fiatTag: "法币支持",
      fiatDescription: "由美元或短期国债支持，锚定稳定性依赖发行方信任与银行交易对手。",
      usgdDescription: "计划由实体黄金进行 150% 抵押，并结合 Ferrari Vault 托管与闭环赎回。",
      lifecycleTitle: "USGD 生命周期",
      lifecycle: [
        ["认购", "上线前投资者发送 USDT。上线后，每 1 美元认购在 BSC 上铸造 1 USGD，并由黄金抵押支持。"],
        ["进入黄金基金", "USGD，或上线前的 USDT，是进入 GODL 质押计划的入口。"],
        ["DeFi 用途", "实验室模型包含 USDT-USGD、GDL-USGD 与 GODL-USGD 池，用于未来分阶段用途。"],
        ["赎回", "本金与收益在 USGD 上线后以 USGD 计入，上线前以 USDT 计入。"],
        ["储备证明", "月度实体库存审计数据设计为上传链上，供公开核验。"],
      ],
      bufferTitle: "抵押缓冲",
      bufferDescription: "拖动实验室金价滑块，模拟抵押缓冲相对于 1 美元锚定的变化。",
      metrics: {
        goldPrice: "黄金价格",
        backing: "每 1 USGD 对应黄金支持",
        buffer: "高于锚定的抵押缓冲",
        fall: "跌破锚定前金价可下跌幅度",
        status: "USGD 锚定状态",
        fullyBacked: "抵押充足",
        belowTarget: "低于目标抵押",
        excess: "超额",
      },
    },
    gdl: {
      title: "GDL 代币经济 - 待开放",
      description: "GDL 治理与激励代币结构正在最终确认。完整分配、归属与回购机制将在 TGE 前公布。",
      kpis: [
        ["总供应量", "10亿", "固定供应，不再增发"],
        ["私募价格", "$0.15", "每枚 GDL"],
        ["融资价 FDV", "1.5亿美元", "持续披露"],
        ["TGE", "2026年9月+", "TGE 前公布完整细节"],
      ],
    },
    faq: {
      intro: "GODL Labs 实验室仪表盘中的机构投资者常见问题确认答复。",
      items: [
        ["是否已获得 VARA 许可？", "Fraktiq DMCC 是我们的迪拜交易实体。VARA 许可申请已获得预批准，目前处于正式化的最后阶段。本仪表盘不声明当前已有有效许可。"],
        [
          "黄金储备由谁审计？",
          "GMRCS 按 JORC Code (2012) 审计，并于 2023 年出具报告。JICUN INTERNATIONAL 持有当前采矿许可证 E734429，新的 2026 JORC 更新正在推进中。",
        ],
        [
          "年度黄金产量是多少？",
          "坦桑尼亚 JORC 储量预计年产 4.6万盎司，基于 100万盎司储量与 4.15 g/t 品位。巴西资产组合暂未纳入当前产量预测或估值。",
        ],
        ["实体黄金由谁托管？", "由 GCC 地区 Ferrari Vault 托管。实体黄金精炼至 99.99% LBMA 标准，并由 Ferrari 提供 2.25 亿美元保险。"],
        [
          "Standard Chartered 的具体角色是什么？",
          "Standard Chartered 负责 GODL RWA 代币在 BSC 上的铸造、数字托管与分发，其交易台也会在每次质押事件中执行即时价格对冲。",
        ],
        ["GODL 收益来自哪里？", "收益模型来自经审计的金矿收入与 AI 黄金对冲网格交易策略。DeFi 池奖励独立存在，并由 GDL 激励额度提供资金。"],
        ["认购和收益支付使用什么货币？", "USGD 上线前，认购与收益支付均以 USDT 结算。USGD 上线后，USGD 将成为同一链上流程的专属入口。"],
        ["当前部署在哪条链？", "当前合约范围使用 BSC，覆盖 GODL、USGD 与 GDL。跨链扩展仍处于规划阶段。"],
        ["TGE 时间是什么？", "GDL Token Generation Event 计划于 2026 年 9 月之后启动，前提是基础设施与监管清晰度达到上市条件。"],
        [
          "如何认购 GODL？",
          "机构用户完成 KYC/KYB、签署认购文件、通过银行汇款 USD 或转入 USDC/USDT，选择锁仓档位，将 GODL 接收到托管地址，并在上线后按月以 USDT 或 USGD 收取收益。",
        ],
      ],
    },
    footer: {
      line1: "GODL Labs Ltd · 开曼群岛 · 机构投资者实验室保密视图 · 2026年5月",
      line2: "预测数字均为前瞻性估算。巴西矿区资产组合未计入财务数据。",
    },
  },
};
